### PR TITLE
Upgrading Akka to version 2.6.3 including fixing deprecation warnings

### PR DESCRIPTION
**Pull request by mmccuiston**
- Upgrading to Akka 2.6.3
- Fixing deprecation warnings including
-- Removing references to ActorMaterializer
-- Changing ScalaTest imports to use new packages/classes from 3.1.0
-- Change test to use non-deprecated constructor for EventSource
-- Use lazySource instead of deprecated lazily factory method for Source

### CODE REVIEW

**Comment by mmccuiston** [comment]
I'm not sure why this was closed without merging.  Do you have any interest in upgrading to Akka 2.6?  Is there anything I can do other that the obvious of fixing the failing cross compile for Scala 2.11?

**Comment by j5ik2o** [comment]
thank you for your contribution!
I want to finish support for 2.11.  So let's move to akka 2.6.  The PullRequests to remove 2.11 from cross-build and migrate to akka2.6 are welcome.

**Comment by j5ik2o** [comment]
close was my mistake.  sorry

**Comment by j5ik2o** [comment]
https://github.com/j5ik2o/akka-persistence-dynamodb/blob/master/.circleci/config.yml#L27
Please remove it.

**Comment by mmccuiston** [comment]
Thanks for reopening!

**Comment by j5ik2o** [comment]
https://jitpack.io/#j5ik2o/akka-persistence-dynamodb/-SNAPSHOT
If you check SNAPSHOT, you can use jitpack.

**Pull request merged**
